### PR TITLE
Update all to 3.0.0-ALPHA11

### LINKED ISSUE #1: Info #Updates #Bugs #Info
- Knockback Booster AKA Redstone RocketPads Doesnt Work
- Some Files Are Not Working.

### PR DESCRIPTION
**Pull request by Adam1609**
## Introduction

The Plugin should be fitted in 1.2 now

### CODE REVIEW

**Comment by HyGlobalHD** [comment]
update all code to 1.2? by the way the rewrite still in-complete.
So if the master branch is okay and use-able i don't mind to update it to 1.2

**Comment by HyGlobalHD** [comment]
@Adam1609 wait a bit i'll invite you to bta

**Comment by MalakasPlayzMC** [comment]
Make a 1.2 branch

**Comment by AcNEO** [comment]
close the pull request, cause pmmp has changed the API so much, that I am too lazy to do it. :P

**Pull request closed without merging**
